---
- name: "import_pipeline | Create Logstash pipeline path: {{ pipeline.name }}"
  register: output
  changed_when: output.size <= 0
  ansible.builtin.file:
    path: "{{ install_logstash_pipelines_path }}/{{ pipeline.name }}"
    state: directory
    recurse: yes
    group: "{{ install_logstash_group }}"
    owner: "{{ install_logstash_user }}"
    mode: "0770"

- name: "import_pipeline | Create Logstash pipeline beat file: {{ pipeline.name }}"
  register: output
  changed_when: output.size <= 0
  ansible.builtin.file:
    path: "{{ install_logstash_pipelines_path }}/{{ pipeline.name }}/beats.conf"
    state: touch
    group: "{{ install_logstash_group }}"
    owner: "{{ install_logstash_user }}"
    mode: "0770"

- name: "import_pipeline | Template Logstash pipeline beat file: {{ pipeline.name }}"
  when: pipeline.name != install_logstash_distributor_pipeline.name
  ansible.builtin.template:
    src: "templates/install_logstash_beats.conf.j2"
    dest: "{{ install_logstash_pipelines_path }}/{{ pipeline.name }}/beats.conf"
    mode: "0770"
    group: "{{ install_logstash_group }}"
    owner: "{{ install_logstash_user }}"
    lstrip_blocks: yes

- name: "import_pipeline | Template Logstash pipeline beat file: {{ pipeline.name }}"
  when: pipeline.name == install_logstash_distributor_pipeline.name
  ansible.builtin.template:
    src: "templates/distributor.conf.j2"
    dest: "{{ install_logstash_pipelines_path }}/{{ pipeline.name }}/{{ pipeline.name }}.conf"
    mode: "0770"
    group: "{{ install_logstash_group }}"
    owner: "{{ install_logstash_user }}"
    lstrip_blocks: yes