---
- name: "import_pipeline | Template Logstash pipeline: {{ pipeline.name }}"
  when: pipeline.name == install_logstash__distributor_pipeline.name or pipeline.name == install_logstash__health_check_pipeline.name
  ansible.builtin.template:
    src: "templates/distributor.conf.j2"
    dest: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}.conf"
    mode: "0700"
    group: "{{ install_logstash__group }}"
    owner: "{{ install_logstash__user }}"
    lstrip_blocks: yes

- name: "import_pipeline | Template Logstash pipeline: {{ pipeline.name }}"
  when: pipeline.name != install_logstash__distributor_pipeline.name and pipeline.name != install_logstash__health_check_pipeline.name
  block:
    - name: "import_pipeline | Create Logstash pipeline path: {{ pipeline.name }}"
      register: output
      changed_when: output.size <= 0
      ansible.builtin.file:
        path: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}"
        state: directory
        recurse: yes
        group: "{{ install_logstash__group }}"
        owner: "{{ install_logstash__user }}"
        mode: "0700"

    - name: "import_pipeline | Template Logstash pipeline beat file: {{ pipeline.name }}"
      ansible.builtin.template:
        src: "templates/beats.conf.j2"
        dest: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}/beats.conf"
        mode: "0700"
        group: "{{ install_logstash__group }}"
        owner: "{{ install_logstash__user }}"
        lstrip_blocks: yes

    - name: "import_pipeline | Template Logstash pipeline output file: {{ pipeline.name }}"
      ansible.builtin.template:
        src: "templates/output.conf.j2"
        dest: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}/output.conf"
        mode: "0700"
        group: "{{ install_logstash__group }}"
        owner: "{{ install_logstash__user }}"
        lstrip_blocks: yes

    - name: "import_pipeline | Template Logstash pipeline template.json file: {{ pipeline.name }}"
      ansible.builtin.template:
        src: "templates/index_template.json.j2"
        dest: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}/template.json"
        mode: "0700"
        group: "{{ install_logstash__group }}"
        owner: "{{ install_logstash__user }}"
        lstrip_blocks: yes

    - name: "import_pipeline | Import Logstash pipeline filter file: {{ pipeline.name }}"
      ansible.builtin.copy:
        src: "files/{{ pipeline.name }}_filter.conf"
        dest: "{{ install_logstash__pipelines_path }}/{{ pipeline.name }}/filter.conf"
        mode: "0700"
        group: "{{ install_logstash__group }}"
        owner: "{{ install_logstash__user }}"
