---
- name: "Enable and start Logstash"
  register: logstash_service_status
  changed_when: not logstash_service_status.state != "started"
  ansible.builtin.service:
    name: "logstash"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Restart Logstash"
  register: logstash_service_status
  changed_when: not logstash_service_status.state != "restarted"
  ansible.builtin.service:
    name: "logstash"
    state: "restarted"
    daemon_reload: true
    enabled: yes
