---
- name: "Enable and start Logstash"
  register: install_logstash__service_status
  changed_when: not install_logstash__service_status.state != "started"
  ansible.builtin.service:
    name: "logstash"
    state: "started"
    daemon_reload: true
    enabled: yes

- name: "Restart Logstash"
  register: install_logstash__service_status
  changed_when: not install_logstash__service_status.state != "restarted"
  ansible.builtin.service:
    name: "logstash"
    state: "restarted"
    daemon_reload: true
    enabled: yes

- name: "Delay Logstash starting"
  ansible.builtin.wait_for:
    delay: 60
    timeout: 0