---
- name: "Converge"
  hosts: "local"
  tasks:

    - name: "Include labocbz.install_logstash"
      tags:
        - "labocbz.install_logstash"
      vars:
        install_logstash__major_version: "{{ inv_install_logstash__major_version }}"
        install_logstash__config_path: "{{ inv_install_logstash__config_path }}"
        install_logstash__ssl_path: "{{ inv_install_logstash__ssl_path }}"
        install_logstash__pipelines_path: "{{ inv_install_logstash__pipelines_path }}"
        install_logstash__pipelines_reload: "{{ inv_install_logstash__pipelines_reload }}"
        install_logstash__pipelines: "{{ inv_install_logstash__pipelines }}"
        install_logstash__health_check_pipeline: "{{ inv_install_logstash__health_check_pipeline }}"
        install_logstash__api: "{{ inv_install_logstash__api }}"
        install_logstash__api_ports: "{{ inv_install_logstash__api_ports }}"
        install_logstash__api_auth_type: "{{ inv_install_logstash__api_auth_type }}"
        install_logstash__api_auth_login: "{{ inv_install_logstash__api_auth_login }}"
        install_logstash__api_auth_password: "{{ inv_install_logstash__api_auth_password }}"
        install_logstash__host: "{{ inv_install_logstash__host }}"
        install_logstash__cluster_name: "{{ inv_install_logstash__cluster_name }}"
        install_logstash__data_path: "{{ inv_install_logstash__data_path }}"
        install_logstash__group: "{{ inv_install_logstash__group }}"
        install_logstash__user: "{{ inv_install_logstash__user }}"
        install_logstash__ram: "{{ inv_install_logstash__ram }}"
        install_logstash__api_ssl: "{{ inv_install_logstash__api_ssl }}"
        install_logstash__api_jks: "{{ inv_install_logstash__api_jks }}"
        install_logstash__api_jks_password: "{{ inv_install_logstash__api_jks_password }}"
        install_logstash__beats_ssl: "{{ inv_install_logstash__beats_ssl }}"
        install_logstash__client_auth: "{{ inv_install_logstash__client_auth }}"
        install_logstash__ssl_authorities: "{{ inv_install_logstash__ssl_authorities }}"
        install_logstash__distributor_pipeline: "{{ inv_install_logstash__distributor_pipeline }}"
        install_logstash__ssl_crt: "{{ inv_install_logstash__ssl_crt }}"
        install_logstash__ssl_key: "{{ inv_install_logstash__ssl_key }}"
        install_logstash__api_p12: "{{ inv_install_logstash__api_p12 }}"
        install_logstash__ssl_p8: "{{ inv_install_logstash__ssl_p8 }}"
        install_logstash__loglevel: "{{ inv_install_logstash__loglevel }}"
        install_logstash__elasticsearch_shard: "{{ inv_install_logstash__elasticsearch_shard }}"
        install_logstash__elasticsearch_ssl: "{{ inv_install_logstash__elasticsearch_ssl }}"
        install_logstash__elasticsearch_login: "{{ inv_install_logstash__elasticsearch_login }}"
        install_logstash__elasticsearch_password: "{{ inv_install_logstash__elasticsearch_password }}"
        install_logstash__elasticsearch_hosts: "{{ inv_install_logstash__elasticsearch_hosts }}"
        install_logstash__elasticsearch_client_auth: "{{ inv_install_logstash__elasticsearch_client_auth }}"
        install_logstash__ssl_elastic: "{{ inv_install_logstash__ssl_elastic }}"
        install_logstash__ssl_elastic_jks: "{{ inv_install_logstash__ssl_elastic_jks }}"
        install_logstash__ssl_elastic_jks_password: "{{ inv_install_logstash__ssl_elastic_jks_password }}"
        install_logstash__ssl_elastic_key: "{{ inv_install_logstash__ssl_elastic_key }}"
        install_logstash__ssl_elastic_crt: "{{ inv_install_logstash__ssl_elastic_crt }}"
        install_logstash__ssl_elastic_p12: "{{ inv_install_logstash__ssl_elastic_p12 }}"
        install_logstash__ssl_elastic_p8: "{{ inv_install_logstash__ssl_elastic_p8 }}"
        install_logstash__ssl_elastic_authorities: "{{ inv_install_logstash__ssl_elastic_authorities }}"
      ansible.builtin.include_role:
        name: "labocbz.install_logstash"
