---
- name: "Converge"
  hosts: "all"
  tasks:
    # replace these tasks with whatever you find suitable to test
    - name: "Copy something to test use of synchronize module"
      ansible.builtin.copy:
        src: "/etc/hosts"
        dest: "/tmp/hosts-from-controller"
        mode: 0700

    - name: "Include labocbz.install_logstash"
      tags:
        - "labocbz.install_logstash"
      vars:
        install_logstash_major_version: "{{ inv_install_logstash_major_version }}"
        install_logstash_config_path: "{{ inv_install_logstash_config_path }}"
        install_logstash_ssl_path: "{{ inv_install_logstash_ssl_path }}"
        install_logstash_pipelines_path: "{{ inv_install_logstash_pipelines_path }}"
        install_logstash_pipelines_reload: "{{ inv_install_logstash_pipelines_reload }}"
        install_logstash_pipelines: "{{ inv_install_logstash_pipelines }}"
        install_logstash_health_check_pipeline: "{{ inv_install_logstash_health_check_pipeline }}"
        install_logstash_api: "{{ inv_install_logstash_api }}"
        install_logstash_api_ports: "{{ inv_install_logstash_api_ports }}"
        install_logstash_api_auth_type: "{{ inv_install_logstash_api_auth_type }}"
        install_logstash_api_auth_login: "{{ inv_install_logstash_api_auth_login }}"
        install_logstash_api_auth_password: "{{ inv_install_logstash_api_auth_password }}"
        install_logstash_host: "{{ inv_install_logstash_host }}"
        install_logstash_cluster_name: "{{ inv_install_logstash_cluster_name }}"
        install_logstash_data_path: "{{ inv_install_logstash_data_path }}"
        install_logstash_group: "{{ inv_install_logstash_group }}"
        install_logstash_user: "{{ inv_install_logstash_user }}"
        install_logstash_ram: "{{ inv_install_logstash_ram }}"
        install_logstash_api_ssl: "{{ inv_install_logstash_api_ssl }}"
        install_logstash_api_jks: "{{ inv_install_logstash_api_jks }}"
        install_logstash_api_jks_password: "{{ inv_install_logstash_api_jks_password }}"
        install_logstash_beats_ssl: "{{ inv_install_logstash_beats_ssl }}"
        install_logstash_client_auth: "{{ inv_install_logstash_client_auth }}"
        install_logstash_ssl_authorities: "{{ inv_install_logstash_ssl_authorities }}"
        install_logstash_distributor_pipeline: "{{ inv_install_logstash_distributor_pipeline }}"
        install_logstash_ssl_crt: "{{ inv_install_logstash_ssl_crt }}"
        install_logstash_ssl_key: "{{ inv_install_logstash_ssl_key }}"
        install_logstash_api_p12: "{{ inv_install_logstash_api_p12 }}"
        install_logstash_ssl_p8: "{{ inv_install_logstash_ssl_p8 }}"
        install_logstash_loglevel: "{{ inv_install_logstash_loglevel }}"
        install_logstash_elasticsearch_shard: "{{ inv_install_logstash_elasticsearch_shard }}"
        install_logstash_elasticsearch_ssl: "{{ inv_install_logstash_elasticsearch_ssl }}"
        install_logstash_elasticsearch_login: "{{ inv_install_logstash_elasticsearch_login }}"
        install_logstash_elasticsearch_password: "{{ inv_install_logstash_elasticsearch_password }}"
        install_logstash_elasticsearch_hosts: "{{ inv_install_logstash_elasticsearch_hosts }}"
        install_logstash_elasticsearch_client_auth: "{{ inv_install_logstash_elasticsearch_client_auth }}"
      ansible.builtin.include_role:
        name: "labocbz.install_logstash"
