---
dependency:
  name: "galaxy"
  options:
    ignore-certs: true

driver:
  name: "docker"

platforms:
  - name: "molecule-local-instance-1-install-logstash"
    image: "labocbz/ansibletest-debian-12:latest"
    hostname: "molecule-local-instance-1-install-logstash"
    privileged: true
    pre_build_image: true
    command: "/sbin/init"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - "/run"
      - "/tmp"
    cgroupns_mode: "host"
    cgroup_manager: "cgroupfs"
    storage_driver: "overlay2"
    networks:
      - name: "molecule-local-instance-1-install-logstash"

provisioner:
  name: "ansible"
  inventory:
    links:
      hosts: "../../tests/inventory/hosts.yml"
      group_vars: "../../tests/inventory/group_vars/"
      host_vars: "../../tests/inventory/host_vars/"
  options:
    extra-vars: "@./tests/tower/tower.yml"
  log: true
  env:
    ANSIBLE_CONFIG: "../../.ansible.cfg"
    ANSIBLE_FORCE_COLOR: "True"
    # disable nologs
    MOLECULE_NOLOG: 0
    # disable destroy
    MOLECULE_DESTROY: "never"
    # debug mode (same as --debug) -- very verbose
    MOLECULE_DEBUG: 1
    # change ansible own verbosity
    ANSIBLE_VERBOSITY: 1

verifier:
  name: "ansible"

scenario:
  name: "default"
  test_sequence:
    - "destroy"
    - "dependency" # need a "requirements.yml" file
    - "syntax"
    - "create"
    - "prepare"
    - "converge"
    - "idempotence"
    - "side_effect" # need a "requirements.yml" file
    - "verify"
    - "destroy"
